services:
  - type: web
    name: gtamini
    runtime: static
    repo: https://github.com/mrauter1/gtamini
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
